name: Security Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: OWASP ZAP Baseline (no upload)
        run: |
          docker pull owasp/zap2docker-stable:latest
          docker run --rm -v $PWD:/zap/wrk \
            owasp/zap2docker-stable zap-baseline.py \
            -t https://abc-air.pythonanywhere.com \
            -r zap_report.html
        continue-on-error: true   # ZAP returns 2 when issues found

      - name: Upload HTML manually (optional)
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap_report.html
